### ISSUE TITLE
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

### ISSUE THREAD

**Issue by Red-ch** [v2ray/discussion#102]
systemctl status v2ray.service 
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-12-26 21:32:19 CST; 7min ago
 Main PID: 927 (v2ray)
    Tasks: 11 (limit: 4641)
   Memory: 25.8M
   CGroup: /system.slice/v2ray.service
           └─927 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
客户端安装完后出现Warning信息，是什么问题？

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
