### ISSUE TITLE
更新脚本或者重装都出现这种问题

### ISSUE THREAD

**Issue by uwtom** [v2ray/discussion#103]
Centos, Debian, Ubuntu环境下都测试过，Vultr和亚马逊安装、更新都是一切正常，但换搬瓦工的机子全新安装不了、更新就出现这样的问题，试过重新做过系统，问题依旧！

![](https://uwtom.github.io/0F9FD107-232C-4039-8918-F193C75DCC73.jpeg)

**Comment by youwei5683** [comment]
在 https://github.com/v2ray/v2ray-core/releases 下载一个对应的客户端上传到vps 。v2ray 服务端和 客户端通用

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
