### ISSUE TITLE
求问如何实现让TCP使用普通TCP协议传输，UDP走mKTP协议传输

### ISSUE THREAD

**Issue by CatSamaaa** [v2ray/discussion#104]
很多联机游戏，连接游戏服务器走的TCP，进了游戏以后就走UDP了，不过我游戏走V2ray代理只能是先一股脑全丢到本地1080端口去，想问下V2ray如何设置可以让监听1080端口后得来的TCP+UDP的数据，TCP就走普通TCP传输协议，UDP走mKCP，
最好能给个参考的配置学习下，感激不尽

**Comment by youwei5683** [comment]
v2ray本身就是 udp转tcp。 不知道udp走mkcp 和 tcp有啥区别。

**Comment by CodeCrazy-guy** [comment]
> 应该是可以，**我没有试过，不保证能够成功**。你需要构建两个outbound，分别为`"tag": "VmessOut"`和`"tag": "mKCPOut"`。一个inbound为`"tag": "SocksIn"`，开启UDP支持。在路由配置中，利用`network`字段以区别不同连接进行路由转发，思路如下：
> 
> ```
>                 {  
>                     "type": "field",  
>                     "network": "tcp",  
>                     "inboundTag": [  
>                         "SocksIn"  
>                     ],  
>                     "outboundTag": "VmessOut"  
>                 },  
>                 {  
>                     "type": "field",  
>                     "network": "udp",  
>                     "inboundTag": [  
>                         "SocksIn"  
>                     ],  
>                     "outboundTag": "mKCPOut"  
>                 }
> ```
> 吐槽一句，你的小鸡或者机场主到底有多抠门，逼得你不得不用这种方式省流量😂

dalao，可否问你一下。

你知道v2ray支持socks5的前置代理吗？

因为我想在v2ray之前配置一个socks5的服务器作为中转。

它是纯socks5协议，而不包含shadowsocks和v2ray的协议。

可以实现吗?

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
