### ISSUE TITLE
Kitsunebi lite 连接断断续续

### ISSUE THREAD

**Issue by duanpingbo** [v2ray/discussion#15]
两台服务器用了两个配置，一台TCP,一台KCP-utp的动态端口，都出现上推特，IG时VPN不停的断开重连。而用shadowrocket配置的TCP端口时则可以正常访问。请问这种问题如何解决，是否是Kitsunebi lite的问题？补充下，此两种配置在PC上都可以正常使用。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest stable version. You can also contribute directly by providing a patch – see the developer manual. :)

Thank you!
