### ISSUE TITLE
Chromebook with v2ray

### ISSUE THREAD

**Issue by Dwonkisu** [v2ray/discussion#19]
朋友用的chromebook，只有酸酸乳插件，能否开启开发者模式下载v2ray-core然后再用插件连接?

**Comment by ToutyRater** [comment]
大约两年前，我对 Chromebook 非常痴迷，于是对在 Chromebook 上怎么科学上网做了大量研究(理论研究)，最后沮丧地发现实现方式都很不优雅，过了这么久好像也没多大改变。不过 [Chrome OS 将允许运行 Linux 软件](https://www.theverge.com/circuitbreaker/2018/5/8/17318340/chrome-os-update-new-features-linux-apps-google-io-2018)，也许这个可以期待一下。

**Comment by PrototypeSeiren** [comment]
我是这样用的,CTRL+ALT+F3,进控制台,然后运行v2ray,没找到设置开机自启动的方法

**Comment by Dwonkisu** [comment]
LInux入门小白，猜想如果ChromeOS用的systemd控制service，可能写个配置文件就能开机自动运行了，不用每次都手动开启了...

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!

**Comment by SquareFong** [comment]
都在考虑开发者模式了，暂且假定你是有办法科学上网的。

在ChromeOS上用v2ray有两种方式。我个人主要使用的安卓App连接，感觉BifrostV还行，Kitsunebi也能用，不过当时好像是碰到了个什么Bug，用起来不方便。。。安卓这种方式会影响整个系统的代理，包括整个Linux容器。缺点是安卓app的运行效率貌似对穿墙速度影响较大，不如core速度快。

另一种方式是通过内置的Linux虚拟机，虚拟机里面是Debian，可以通过systemd进行打开容器即开启v2ray，chrome再通过switchyomega设置代理。这个不影响安卓App的代理，play商店无法使用。Linux容器有一定几率在睡眠再唤醒之后，CPU占用率莫名变高，导致系统卡顿，需要关闭Linux虚拟机后重启打开一遍。

至于开机自动启动，个人感觉不重要，ChomeBook开盖唤醒很快，休眠也不费电，除非更新我都不怎么关机，没考虑这个问题，所以没有研究。。。

**Comment by d3vw** [comment]
https://github.com/chromebrew/chromebrew
