### ISSUE TITLE
v2ray单用户与多用户区别 有什么区别 

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/discussion#22]
From v2ray-core created by [lxyg06](https://github.com/lxyg06) : v2ray/v2ray-core#1247  

我多客户端 配置都是同一个id和 多客户端配置不同的id  这两个有什么区别吗

**Comment by Cwek** [comment]
没有吧，多Id的话方便管理。（结合现在的API对vmess的配置动态插拔，流量总数的话还要结合统计API来计数）

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
