### ISSUE TITLE
通过dokodemo-door桥接socks代理出现timeout

### ISSUE THREAD

**Issue by phantomedc** [v2ray/discussion#245]
公司内部有一个http proxy，所有上网流量都需要走这个http代理，在ssr情况下，这就是一个前置代理。
现在使用v2ray时，希望通过v2ray的链式代理特性，实现科学上网，配置如下：
```
{
	"log": {
		"access": "C:/Users/..../Desktop/v2ray/access.log",
		"error": "C:/Users/..../Desktop/v2ray/error.log",
		"loglevel": "warn"
	},
	"inbound": {
		"port": 1082,
		"listen": "0.0.0.0",
		"protocol": "http",
		"sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
		"settings": {
			"auth": "noauth"
		},
		"mux":{
			"enabled":true
		}
		
	},
	"outbound": {
		"protocol": "vmess",
		"settings": {
			"vnext": [{
				"address": "127.0.0.1",
				"port": 1099,
				"users": [{
					"id": "my-vmess-id",
					"alterId": 233
				}]
			}]
		},
		"streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {
		"path":"/",
        "headers": {
          "Host": "domain.me"
        }
      },
      "tlsSettings": {
        "serverName": "domain.me"
      }
    }
	},
	"inboundDetour":[{
		"listen": "127.0.0.1",
		"port":1099,
		"protocol":"dokodemo-door",
		"settings":{
			"network":"tcp",
			"address":"domain.me",
			"port":443
		},
		"tag":"bridge"
	}
	],
//以下是通过h2s将公司的http代理转换成socks代理，监听在1081端口，
	"outboundDetour": [{
		"protocol": "socks",
		"settings": {
			"servers": [{
				"address": "127.0.0.1",
				"port": 1081
			}]
		},
		"tag": "h2s"
	}],
	"routing": {
		"strategy": "rules",
		"settings": {
			"rules": [{
				"type": "field",
				"inboundTag": [
					"bridge"
				],
				"outboundTag": "h2s",
				"domain":["geosite:geolocation-!cn"]
			}]
		}
	}
}   
```
服务启动以后，一直报错：
```
2019/06/06 16:38:15 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62311->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62321->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62330->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62340->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62349->127.0.0.1:1099: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/06 16:38:17 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62316->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62324->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62334->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62344->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > EOF] > v2ray.com/core/common/retry: all retry attempts failed
2019/06/06 16:39:00 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62362->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62369->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62378->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62387->127.0.0.1:1099: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://127.0.0.1:1099/):  > read tcp 127.0.0.1:62395->127.0.0.1:1099: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

```

思路参考：[链式代理与透明代理：V2Ray 的进阶用法](https://kirikira.moe/post/26/#2)

通过抓包发现，当outbound尝试与dokodemo-door建立连接时，出现了
![屏幕快照 2019-06-06 下午5 14 35](https://user-images.githubusercontent.com/15801693/59021556-98a94e00-887e-11e9-9870-47af6129dd97.png)
![屏幕快照 2019-06-06 下午5 14 26](https://user-images.githubusercontent.com/15801693/59021561-9a731180-887e-11e9-83fd-b65c4cbf2625.png)

`This is a TCP duplicate ack`

**Comment by xiaokangwang** [comment]
你这个代理配置的outbound中，我没有找到 proxySettings/tag。V2Ray根据这个来确定链式转发时下一个跃点是什么。请参考 https://toutyrater.github.io/advanced/outboundproxy.html

**Comment by xiaokangwang** [comment]
后来的私下讨论中认为是rule设置不当，产生了环回

**Comment by phantomedc** [comment]
> 后来的私下讨论中认为是rule设置不当，产生了环回

今天回到公司尝试了一下，并非rule的问题，仍然出现tcp乱序的问题。

**Comment by phantomedc** [comment]
已经解决

**Comment by andychenkk** [comment]
> 已经解决

你好。我所在的网络环境和你相似，请教下你怎样解决的？非常感谢。

**Comment by andychenkk** [comment]
> > 后来的私下讨论中认为是rule设置不当，产生了环回
> 
> 今天回到公司尝试了一下，并非rule的问题，仍然出现tcp乱序的问题。
你好。我所在的网络环境和你相似，请教下你怎样解决的？非常感谢。 @phantomedc

**Comment by phantomedc** [comment]
> > > 后来的私下讨论中认为是rule设置不当，产生了环回
> > 
> > 
> > 今天回到公司尝试了一下，并非rule的问题，仍然出现tcp乱序的问题。
> > 你好。我所在的网络环境和你相似，请教下你怎样解决的？非常感谢。 @phantomedc

请把你的场景以及你现在的配置贴一下

**Comment by andychenkk** [comment]
// Config file of V2Ray. This file follows standard JSON format, with comments support.
// Uncomment entries below to satisfy your needs. Also read our manual for more detail at
// https://www.v2ray.com/
{
  "log": {
    // By default, V2Ray writes access log to stdout.
    // "access": "/path/to/access/log/file",

    // By default, V2Ray write error log to stdout.
    // "error": "/path/to/error/log/file",

    // Log level, one of "debug", "info", "warning", "error", "none"
    "loglevel": "warning"
  },
  // List of inbound proxy configurations.
  "inbounds": [{
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 1080,

    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces.
    "listen": "0.0.0.0",

    // Tag of the inbound proxy. May be used for routing.
    "tag": "socks-inbound",

    // Protocol name of inbound proxy.
    "protocol": "socks",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    },

    // Enable sniffing on TCP connection.
    "sniffing": {
      "enabled": true,
      // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.
      "destOverride": ["http", "tls"]
    }
  }],
  // List of outbound proxy configurations.
  "outbounds": [{
    "protocol": "socks",
    "settings":{
  "servers": [{
    "address": "*****",
    "port": 8081,
    "users": [
      {
       "user": "******",
        "pass": "*****",
       "level": 1
     }
    ]
  }]
},
     "proxySettings": {
    "tag": "centProxy"
  }
  },{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "*****", // 服务器地址，请修改为你自己的服务器 ip 或域名
        "port": ****,  // 服务器端口
        "users": [{ "id": "fabb3b88-********7d491f9e5652" ,
        "alterId": 64, // 此处的值也应当与服务器相同
        "security": "auto",
        "level": 1
        	}]
      }]
    },
    "tag": "centProxy"

  }
  ,{
    // Protocol name of the outbound proxy.
    "protocol": "freedom",

    // Settings of the protocol. Varies based on protocol.
    "settings": {},

    // Tag of the outbound. May be used for routing.
    "tag": "direct"
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],

  // Transport is for global transport settings. If you have multiple transports with same settings
  // (say mKCP), you may put it here, instead of in each individual inbound/outbounds.
  //"transport": {},

  // Routing controls how traffic from inbounds are sent to outbounds.
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        // Blocks access to private IPs. Remove this if you want to access your router.
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      },
      {
        // Blocks major ads.
        "type": "field",
        "domain": ["geosite:category-ads"],
        "outboundTag": "blocked"
      }
    ]
  },

  // Dns settings for domain resolution.
  "dns": null,

  // Policy controls some internal behavior of how V2Ray handles connections.
  // It may be on connection level by user levels in 'levels', or global settings in 'system.'
  "policy": {

  },

  // Stats enables internal stats counter.
  // This setting can be used together with Policy and Api.
  //"stats":{},

  // Api enables gRPC APIs for external programs to communicate with V2Ray instance.
  //"api": {
    //"tag": "api",
    //"services": [
    //  "HandlerService",
    //  "LoggerService",
    //  "StatsService"
    //]
  //},

  // You may add other entries to the configuration, but they will not be recognized by V2Ray.
  "other": {}
}

@phantomedc   我现客户端所在的局域网需通过局域网代理服务器才能上外网，现在需连接vps上的服务器端（原先ss客户端中将局域网代理服务信息配置在正向代理中可以成功连接vps的）。配置是根据v2ray-windows-64 压缩包中的原来的config文件进行修改，设置了proxySettings，但是不行。快2周了还是没找到方法。非常感谢你的指导。

**Comment by andychenkk** [comment]
// Config file of V2Ray. This file follows standard JSON format, with comments support.
// Uncomment entries below to satisfy your needs. Also read our manual for more detail at
// https://www.v2ray.com/
{
"log": {
// By default, V2Ray writes access log to stdout.
// "access": "/path/to/access/log/file",
// By default, V2Ray write error log to stdout. // "error": "/path/to/error/log/file", // Log level, one of "debug", "info", "warning", "error", "none" "loglevel": "warning" 
},
// List of inbound proxy configurations.
"inbounds": [{
// Port to listen on. You may need root access if the value is less than 1024.
"port": 1080,
// IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces. "listen": "0.0.0.0", // Tag of the inbound proxy. May be used for routing. "tag": "socks-inbound", // Protocol name of inbound proxy. "protocol": "socks", // Settings of the protocol. Varies based on protocol. "settings": {   "auth": "noauth",   "udp": true,   "ip": "127.0.0.1" }, // Enable sniffing on TCP connection. "sniffing": {   "enabled": true,   // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.   "destOverride": ["http", "tls"] } 
}],
// List of outbound proxy configurations.
"outbounds": [{
"protocol": "socks",
"settings":{
"servers": [{
"address": "",
"port": 8081,
"users": [
{
"user": "",
"pass": "",
"level": 1
}
]
}]
},
"proxySettings": {
"tag": "centProxy"
}
},{
"protocol": "vmess",
"settings": {
"vnext": [{
"address": "*", // 服务器地址，请修改为你自己的服务器 ip 或域名
"port": ****, // 服务器端口
"users": [{ "id": "fabb3b88-********7d491f9e5652" ,
"alterId": 64, // 此处的值也应当与服务器相同
"security": "auto",
"level": 1
}]
}]
},
"tag": "centProxy"

}
,{
// Protocol name of the outbound proxy.
"protocol": "freedom",
// Settings of the protocol. Varies based on protocol. "settings": {}, // Tag of the outbound. May be used for routing. "tag": "direct" 
},{
"protocol": "blackhole",
"settings": {},
"tag": "blocked"
}],

// Transport is for global transport settings. If you have multiple transports with same settings
// (say mKCP), you may put it here, instead of in each individual inbound/outbounds.
//"transport": {},

// Routing controls how traffic from inbounds are sent to outbounds.
"routing": {
"domainStrategy": "IPOnDemand",
"rules":[
{
// Blocks access to private IPs. Remove this if you want to access your router.
"type": "field",
"ip": ["geoip:private"],
"outboundTag": "blocked"
},
{
// Blocks major ads.
"type": "field",
"domain": ["geosite:category-ads"],
"outboundTag": "blocked"
}
]
},

// Dns settings for domain resolution.
"dns": null,

// Policy controls some internal behavior of how V2Ray handles connections.
// It may be on connection level by user levels in 'levels', or global settings in 'system.'
"policy": {

},

// Stats enables internal stats counter.
// This setting can be used together with Policy and Api.
//"stats":{},

// Api enables gRPC APIs for external programs to communicate with V2Ray instance.
//"api": {
//"tag": "api",
//"services": [
// "HandlerService",
// "LoggerService",
// "StatsService"
//]
//},

// You may add other entries to the configuration, but they will not be recognized by V2Ray.
"other": {}
}

@phantomedc 我现客户端所在的局域网需通过局域网代理服务器才能上外网，现在需连接vps上的服务器端（原先ss客户端中将局域网代理服务信息配置在正向代理中可以成功连接vps的）。配置是根据v2ray-windows-64 压缩包中的原来的config文件进行修改，设置了proxySettings，但是不行。快2周了还是没找到方法。非常感谢你的指导。




------------------ 原始邮件 ------------------
发件人: "Shuo"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午3:46
收件人: "v2ray/discussion"<discussion@noreply.github.com>;
抄送: "Andy"<andy_chen_kk@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [v2ray/discussion] 通过dokodemo-door桥接socks代理出现timeout (#245)



   
后来的私下讨论中认为是rule设置不当，产生了环回
  
今天回到公司尝试了一下，并非rule的问题，仍然出现tcp乱序的问题。
 你好。我所在的网络环境和你相似，请教下你怎样解决的？非常感谢。 @phantomedc
   
请把你的场景以及你现在的配置贴一下

**Comment by andychenkk** [comment]
// Config file of V2Ray. This file follows standard JSON format, with comments support.
// Uncomment entries below to satisfy your needs. Also read our manual for more detail at
// https://www.v2ray.com/
{
"log": {
// By default, V2Ray writes access log to stdout.
// "access": "/path/to/access/log/file",
// By default, V2Ray write error log to stdout. // "error": "/path/to/error/log/file", // Log level, one of "debug", "info", "warning", "error", "none" "loglevel": "warning"  
},
// List of inbound proxy configurations.
"inbounds": [{
// Port to listen on. You may need root access if the value is less than 1024.
"port": 1080,
// IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces. "listen": "0.0.0.0", // Tag of the inbound proxy. May be used for routing. "tag": "socks-inbound", // Protocol name of inbound proxy. "protocol": "socks", // Settings of the protocol. Varies based on protocol. "settings": {   "auth": "noauth",   "udp": true,   "ip": "127.0.0.1" }, // Enable sniffing on TCP connection. "sniffing": {   "enabled": true,   // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.   "destOverride": ["http", "tls"] }  
}],
// List of outbound proxy configurations.
"outbounds": [{
"protocol": "socks",
"settings":{
"servers": [{
"address": "",
"port": 8081,
"users": [
{
"user": "",
"pass": "",
"level": 1
}
]
}]
},
"proxySettings": {
"tag": "centProxy"
}
},{
"protocol": "vmess",
"settings": {
"vnext": [{
"address": "*", // 服务器地址，请修改为你自己的服务器 ip 或域名
"port": ****, // 服务器端口
"users": [{ "id": "fabb3b88-********7d491f9e5652" ,
"alterId": 64, // 此处的值也应当与服务器相同
"security": "auto",
"level": 1
}]
}]
},
"tag": "centProxy"
 
}
,{
// Protocol name of the outbound proxy.
"protocol": "freedom",
// Settings of the protocol. Varies based on protocol. "settings": {}, // Tag of the outbound. May be used for routing. "tag": "direct"  
},{
"protocol": "blackhole",
"settings": {},
"tag": "blocked"
}],
 
// Transport is for global transport settings. If you have multiple transports with same settings
// (say mKCP), you may put it here, instead of in each individual inbound/outbounds.
//"transport": {},
 
// Routing controls how traffic from inbounds are sent to outbounds.
"routing": {
"domainStrategy": "IPOnDemand",
"rules":[
{
// Blocks access to private IPs. Remove this if you want to access your router.
"type": "field",
"ip": ["geoip:private"],
"outboundTag": "blocked"
},
{
// Blocks major ads.
"type": "field",
"domain": ["geosite:category-ads"],
"outboundTag": "blocked"
}
]
},
 
// Dns settings for domain resolution.
"dns": null,
 
// Policy controls some internal behavior of how V2Ray handles connections.
// It may be on connection level by user levels in 'levels', or global settings in 'system.'
"policy": {
 
},
 
// Stats enables internal stats counter.
// This setting can be used together with Policy and Api.
//"stats":{},
 
// Api enables gRPC APIs for external programs to communicate with V2Ray instance.
//"api": {
//"tag": "api",
//"services": [
// "HandlerService",
// "LoggerService",
// "StatsService"
//]
//},
 
// You may add other entries to the configuration, but they will not be recognized by V2Ray.
"other": {}
}
 
@phantomedc 我现客户端所在的局域网需通过局域网代理服务器才能上外网，现在需连接vps上的服务器端（原先ss客户端中将局域网代理服务信息配置在正向代理中可以成功连接vps的）。配置是根据v2ray-windows-64 压缩包中的原来的config文件进行修改，设置了proxySettings，但是不行。快2周了还是没找到方法。非常感谢你的指导。

**Comment by phantomedc** [comment]
@andychenkk 你需要确定：
1.你司的代理服务是http协议还是socks协议，v2ray只支持socks协议。
2.你服务端的v2ray是基于朴素tcp还是ws+tls+web？只有朴素tcp的情况下才适用于proxySettings的配置

**Comment by andychenkk** [comment]
> @andychenkk 你需要确定：
> 1.你司的代理服务是http协议还是socks协议，v2ray只支持socks协议。
> 2.你服务端的v2ray是基于朴素tcp还是ws+tls+web？只有朴素tcp的情况下才适用于proxySettings的配置

1.是http；
2.服务端inbound是vmess协议，是tcp。
服务器配置如下：
{

  "log": {
  "access": "/tmp/v2ray/v2rayaccess.log",
  "error": "/tmp/v2ray/v2rayerror.log",
  "loglevel": "warning"
  },
  "inbounds": [{
    "port": 10086,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "fabb3b8*****7d491f9e5652",
          "level": 1,
          "alterId": 64
        }
      ]
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}
@phantomedc

**Comment by phantomedc** [comment]
@andychenkk 
你们的内部代理服务器是http，那么v2ray是无法直接使用它的，需要使用[h2s](https://github.com/Equim-chan/h2s)来把它convert成为socks代理
然后你的outbound配置应该是：
```
"outbounds": [{
		"protocol": "vmess",
		"settings": {
			"vnext": [{
				"address": "xx.xx.xx.xx",
				"port": xxxx,
				"users": [{
					"id": "xxxxxx-xxxxx-xxx-xxxx-xxxxxxx",
					"alterId": xxxx,
					"security": "auto"
				}]
			}]
		},
		"proxySettings":{
			"tag":"h2s"
		},
		"mux": {
			"enabled": true
		}
	}, {
		"protocol": "freedom",
		"settings": {},
		"tag": "direct"
	},{
		"protocol":"socks",
		"settings":{
			"servers":[{
				"address":"127.0.0.1",
			"port":1081
			}]
		},
		"tag":"h2s"
	}],
```

**Comment by andychenkk** [comment]
@phantomedc   好的。服务端应该不用改吧。 我先了解下h2f 怎么安装，再配置试试，感谢感谢。
