### ISSUE TITLE
希望提供配置项“ 关闭时间验证 ”

### ISSUE THREAD

**Issue by veekxt** [v2ray/discussion#26]
有时候客户端真的需要不准确的时间并且不关心重放攻击。

**Comment by Rucc1** [comment]
参考：https://www.v2ray.com/developer/protocols/vmess.html#%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF
目前 vmess 协议头认证需要 8 byte 的时间作为 HMAC 的参数；
如取消时间认证，可能需要设计全新的协议。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
