### ISSUE TITLE
路由器客户端有被官方认可的吗

### ISSUE THREAD

**Issue by channingbox** [v2ray/discussion#27]
目前知道的都是被集成到第三方lede固件里的 例如 lean固件等

**Comment by channingbox** [comment]
我只想安装官方编译的lede，再安装 v2ray路由器apk

**Comment by channingbox** [comment]
得益于golang的静态编译，搞了个简易版：https://github.com/wongsyrone/openwrt-v2ray
@wongsyrone 这是王同学编译的版本

**Comment by cherrot** [comment]
可以参考 <https://steemit.com/cn/@v2ray/meemg-v2ray> 自行编译
服务管理(`/etc/init.d/xxx`)可以参考<https://github.com/cherrot/openwrt_pangolin>
:)

**Comment by channingbox** [comment]
@cherrot 谢谢你 我研究一下

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
