### ISSUE TITLE
安卓平台没有像 shadowrocket 这样的客户端吗

### ISSUE THREAD

**Issue by channingbox** [v2ray/discussion#33]
采用 Flutter.io 这样的设计方案，现在得都太简陋或者功能有限。适当收费也是可以接受的。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
