### ISSUE TITLE
v2ray无法启动的情况

### ISSUE THREAD

**Issue by m250317460** [v2ray/discussion#365]
使用v2ray的选项启动之后提示v2ray已经启动，但是我用systemctl status v2ray.service 检测发现v2ray没有启动，错误消息是
Sep 12 18:27:09 v90305.kvm.u42317.com systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 12 18:27:09 v90305.kvm.u42317.com systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 12 18:27:09 v90305.kvm.u42317.com systemd[1]: Failed to start V2Ray Service.
现在我已经不知道该怎么办了,ballball各位大佬救救孩子吧

**Comment by iochen** [comment]
> Start request repeated too quickly.

Try
`systemctl restart v2ray`

**Comment by kslr** [comment]
不要使用systemd 直接启动程序测试

或者使用v2ray -test命令

**Comment by aaron-trip** [comment]
最后怎么样，解决了吗？我也遇到了同样的问题，如果解决了，帮忙分享一下，谢谢 @m250317460

**Comment by robertlee22** [comment]
我也遇到了(code=exited, status=255) 问题。已解决。我的情况是已经运行了一个v2ray，正在占用了端口，关闭掉正在运行的进程，systemctl restart v2ray就可以了。

**Comment by marychu8831** [comment]
> 使用v2ray -test命令


> > > Start request repeated too quickly.
> > 
> > 
> > Try
> > `systemctl restart v2ray`
> 
> After `systemctl restart v2ray`, I typed `systemctl status v2ray.service` The screenshot was still: `v2ray.service - V2Ray Service Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: e Active: failed (Result: exit-code) since Tue 2019-10-08 22:47:18 CST; 2s ago Process: 9505 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (c Main PID: 9505 (code=exited, status=255)
> 
> 10月 08 22:47:18 tp systemd[1]: v2ray.service: Service hold-off time over, sched 10月 08 22:47:18 tp systemd[1]: v2ray.service: Scheduled restart job, restart co 10月 08 22:47:18 tp systemd[1]: Stopped V2Ray Service. 10月 08 22:47:18 tp systemd[1]: v2ray.service: Start request repeated too quickl 10月 08 22:47:18 tp systemd[1]: v2ray.service: Failed with result 'exit-code'. 10月 08 22:47:18 tp systemd[1]: Failed to start V2Ray Service. `

这个问题解决了吗？ 我也存在同样的问题。麻烦请指教下，谢谢！

**Comment by aaron-trip** [comment]
谢谢，后来我放弃它了。。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v2ray/discussion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [v2ray/discussion] v2ray无法启动的情况 (#365)





  
使用v2ray -test命令
     
Start request repeated too quickly.
  
Try
 systemctl restart v2ray
  
After systemctl restart v2ray, I typed systemctl status v2ray.service The screenshot was still: `v2ray.service - V2Ray Service Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: e Active: failed (Result: exit-code) since Tue 2019-10-08 22:47:18 CST; 2s ago Process: 9505 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (c Main PID: 9505 (code=exited, status=255)
 
10月 08 22:47:18 tp systemd[1]: v2ray.service: Service hold-off time over, sched 10月 08 22:47:18 tp systemd[1]: v2ray.service: Scheduled restart job, restart co 10月 08 22:47:18 tp systemd[1]: Stopped V2Ray Service. 10月 08 22:47:18 tp systemd[1]: v2ray.service: Start request repeated too quickl 10月 08 22:47:18 tp systemd[1]: v2ray.service: Failed with result 'exit-code'. 10月 08 22:47:18 tp systemd[1]: Failed to start V2Ray Service. `
  
这个问题解决了吗？ 我也存在同样的问题。麻烦请指教下，谢谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
