### ISSUE TITLE
what is wrong ？

### ISSUE THREAD

**Issue by qimeila** [v2ray/discussion#37]
rejected  v2ray.com/core/proxy/socks: insufficient header > read tcp 127.0.0.1:2333->127.0.0.1:7658: i/o timeout

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
