### ISSUE TITLE
建议通过命令行参数的方式开启流量查询功能

### ISSUE THREAD

**Issue by ghost** [v2ray/discussion#38]
现在想开启流量查询要在config.json中添加很多行配置。而每个用户（是指个人不是指config.json中的帐户）的配置又千差万别， 没法通过添加固定配置的方式来解决。目前要么针对每个配置来修改，要么限制用户只能修改少部分配置。两种方式都很不灵活。

建议添加通过命令行参数开启流量统计功能。
例如： ./v2ray --stat 127.0.0.1:1081
使用浏览器或者curl访问这个地址的时候会得到一个包含两个数值的字符串，分别表示从v2ray-core启动到查询为止的上行/下行总数据量。只是单向的查询就可以，不需要重置，不需要按帐号查询等高级功能。这样用户就可以很方便的查到流量耗用数据。

**Comment by Cwek** [comment]
作为服务端的流量管理？
应该是用API来操作吧？用HandlerService来插拔vmess用户的接入，真实用户直接用id或user辨识区分，用StatsService来监测user的流量数。分发给用户的配置只有一个outbound的完整文件，或者分发后让他们自行调整。

**Comment by c16ee5a6** [comment]
所有数据都和core打交道，开发前端还是要从core查流量啊。
除非在core外面再包一层proxy或者从网卡全局监控才可以绕开core，不过这有点overkill吧。

**Comment by Cwek** [comment]
其实就是开发一个外围程序，去访问core来读取数据。而不是直接由core实现这个外围功能。

**Comment by c16ee5a6** [comment]
首先这个外围程序只能解决后半部分的查询问题。其次要是通过grpc查询那么这个外围程序已经存在就是v2ctl。这个issue要说的重点是目前查流量太复杂了，对于服务端也许必须这么复杂，然而对于客户端其实可以做得简单一些。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
