### ISSUE TITLE
v2ray invoked oom-killer

### ISSUE THREAD

**Issue by winds365** [v2ray/discussion#46]
我512M的VPS，出现v2ray invoked oom-killer然后死机，发生不只一次了
v2ray版本3.50（以前版本也发生过）
下面是服务器日志，10月30日当天，并没有使用v2ray
[LS_2018-11-01_00-55-59.log](https://github.com/v2ray/discussion/files/2535632/LS_2018-11-01_00-55-59.log)

**Comment by cnchill** [comment]
现在都 4.10.0了，有试过没

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
