### ISSUE TITLE
Kali Linux系统支持V2ray吗？

### ISSUE THREAD

**Issue by voltwu** [v2ray/discussion#478]
我有一台Kali系统的电脑，需要装上V2ray的客户端。V2ray服务端已经有了，并且我的另一台Windows系统已经能够代理上网了。 现在需要在这台Kali Linux系统的电脑上装上V2ray客户端。我尝试过很多次，都失败了。
安装的过程中，并没有显示有什么错误。当我下载好V2ray-core 4.20后，解压后运行：
`./v2ray -config=config.json`
启动v2ray，启动后没有报错。
```
root@kali:~/Desktop/v2ray/# ./v2ray -config=config.json 

V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom

A unified platform for anti-censorship.

2019/12/28 16:04:11 [Warning] v2ray.com/core: V2Ray 4.20.0 started

2019/12/28 16:05:38 tcp:127.0.0.1:35982 accepted tcp:google.com:80 
```
我设置好了系统代理，但是当我访问访问Google.com的时候，依然不成功。

我的V2ray-core版本是4.20的。

**Comment by kslr** [comment]
try https://www.google.com

**Comment by voltwu** [comment]
Thank you. I tried but failed. I watched the document [here](https://www.v2ray.com/en/welcome/install.html). it says:

> Including but not limited to Debian 7 / 8, Ubuntu 12.04 / 14.04 and later, CentOS 6 / 7, Arch Linux

So, I searched for some articles. about install V2ray on Kali is rare.  So I vagued that platforms that V2ray support.

**Comment by kslr** [comment]
I mean your work is normal, try visiting https link

**Comment by voltwu** [comment]
Sorry, It's still not working.

**Comment by ShawKW** [comment]
https://fengwenhua.top/archives/kali%E5%AE%89%E8%A3%85v2ray
have a try

**Comment by overheat** [comment]
@ShawKW 按照你的blog，可以把chromium成功google了。但是其他没有用proxychians的软件，比如firefox就不能用了。。。

**Comment by beesuns** [comment]
@overheat 请教一下：
按照 [v2ray](https://www.v2ray.com/chapter_00/install.html)  **go.sh参数**  关于通过本地文件进行安装的说明，成功安装了 v2ray 到 Kali Live USB。
`root@kali:~# bash <(curl -L -s https://install.direct/go.sh) --local /home/kali/Desktop/v2ray-linux-64.zip
Installing V2Ray via local file. Please make sure the file is a valid V2Ray package, as we are not able to determine that.
Archive:  /home/kali/Desktop/v2ray-linux-64.zip
  inflating: /usr/bin/v2ray/geoip.dat  
  inflating: /usr/bin/v2ray/geosite.dat  
  inflating: /usr/bin/v2ray/v2ctl    
  inflating: /usr/bin/v2ray/v2ray    
PORT:16669
UUID:d8a235b4-8d1e-4dea-90d9-de452119d342
Archive:  /home/kali/Desktop/v2ray-linux-64.zip
  inflating: /etc/systemd/system/v2ray.service  
Created symlink /etc/systemd/system/multi-user.target.wants/v2ray.service → /etc/systemd/system/v2ray.service.
V2Ray local is installed.`

@ShawKW 按照您博客中提到的方法，在修改proxychains.conf文件的时候，试过1080，10808和8080这三个端口，均未成功。
`root@kali:~# systemctl enable /etc/systemd/system/v2ray.service
root@kali:~# systemctl restart v2ray.service
root@kali:~# systemctl status v2ray.service
● v2ray.service - V2Ray Service
     Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor pr>
     Active: active (running) since Fri 2020-05-08 00:45:13 UTC; 10s ago
   Main PID: 26559 (v2ray)
      Tasks: 14 (limit: 9186)
     Memory: 9.7M
     CGroup: /system.slice/v2ray.service
             └─26559 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

May 08 00:45:13 kali systemd[1]: Started V2Ray Service.
May 08 00:45:13 kali v2ray[26559]: V2Ray 4.23.1 (V2Fly, a community-driven>
May 08 00:45:13 kali v2ray[26559]: A unified platform for anti-censorship.
May 08 00:45:14 kali v2ray[26559]: 2020/05/08 00:45:14 [Info] v2ray.com/co>
May 08 00:45:14 kali v2ray[26559]: v2ctl> Read config:  /etc/v2ray/config.>
May 08 00:45:14 kali v2ray[26559]: 2020/05/08 00:45:14 [Warning] v2ray.com>
root@kali:~# vim /etc/proxychains.conf
root@kali:~# cp /usr/lib/proxychains3/proxyresolv /usr/bin/

root@kali:~# proxyresolv www.google.com
|S-chain|-<>-127.0.0.1:1080-<--timeout

root@kali:~# proxyresolv www.google.com
|S-chain|-<>-127.0.0.1:10808-<--timeout

root@kali:~# proxyresolv www.google.com
|S-chain|-<>-127.0.0.1:8080-<--timeout`

proxychains.conf文件如下：

`# proxychains.conf  VER 3.1
#
#        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
#	

# The option below identifies how the ProxyList is treated.
# only one option should be uncommented at time,
# otherwise the last appearing option will be accepted
#
dynamic_chain
#
# Dynamic - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# at least one proxy must be online to play in chain
# (dead proxies are skipped)
# otherwise EINTR is returned to the app
#
strict_chain
#
# Strict - Each connection will be done via chained proxies
# all proxies chained in the order as they appear in the list
# all proxies must be online to play in chain
# otherwise EINTR is returned to the app
#
#random_chain
#
# Random - Each connection will be done via random proxy
# (or proxy chain, see  chain_len) from the list.
# this option is good to test your IDS :)

# Make sense only if random_chain
#chain_len = 2

# Quiet mode (no output from library)
#quiet_mode

# Proxy DNS requests - no leak for DNS data
proxy_dns 

# Some timeouts in milliseconds
tcp_read_time_out 15000
tcp_connect_time_out 8000

# ProxyList format
#       type  host  port [user pass]
#       (values separated by 'tab' or 'blank')
#
#
#        Examples:
#
#            	socks5	192.168.67.78	1080	lamer	secret
#		http	192.168.89.3	8080	justu	hidden
#	 	socks4	192.168.1.49	1080
#	        http	192.168.39.93	8080	
#		
#
#       proxy types: http, socks4, socks5
#        ( auth types supported: "basic"-http  "user/pass"-socks )
#
[ProxyList]
# add proxy here ...
# meanwile
# defaults set to "tor"
#socks4 	127.0.0.1 9050
socks5	127.0.0.1 8080	
`

**Comment by ShawKW** [comment]
> @ShawKW 按照你的blog，可以把chromium成功google了。但是其他没有用proxychians的软件，比如firefox就不能用了。。


yes
in fact in the kali 1.0 you can use  the  network setting 
but in the kali 2.0 I dont find any other way to reach VPS without proxychain
and if U want to use firefox that have a try ...
"proxychain firefox"
if U dont success maybe U dont set proxy well  in the firefox

**Comment by ShawKW** [comment]
> @overheat 请教一下：
> 按照 [v2ray](https://www.v2ray.com/chapter_00/install.html) **go.sh参数** 关于通过本地文件进行安装的说明，成功安装了 v2ray 到 Kali Live USB。并根据自己搭建的 v2ray 服务器端 config.json 文件配置修改了 v2ray 客户端 config.json 文件
> 
> ```
> root@kali:~# bash <(curl -L -s https://install.direct/go.sh) --local /home/kali/Desktop/v2ray-linux-64.zip
> Installing V2Ray via local file. Please make sure the file is a valid V2Ray package, as we are not able to determine that.
> Archive:  /home/kali/Desktop/v2ray-linux-64.zip
>   inflating: /usr/bin/v2ray/geoip.dat  
>   inflating: /usr/bin/v2ray/geosite.dat  
>   inflating: /usr/bin/v2ray/v2ctl    
>   inflating: /usr/bin/v2ray/v2ray    
> PORT:16669
> UUID:d8a235b4-8d1e-4dea-90d9-de452119d342
> Archive:  /home/kali/Desktop/v2ray-linux-64.zip
>   inflating: /etc/systemd/system/v2ray.service  
> Created symlink /etc/systemd/system/multi-user.target.wants/v2ray.service → /etc/systemd/system/v2ray.service.
> V2Ray local is installed.
> ```
> 
> @ShawKW 按照您博客中提到的方法，在修改**proxychains.conf**文件的时候，试过**1080**，**10808**和**8080**这三个端口，均未成功。
> 
> ```
> root@kali:~# systemctl enable /etc/systemd/system/v2ray.service
> root@kali:~# systemctl restart v2ray.service
> root@kali:~# systemctl status v2ray.service
> ● v2ray.service - V2Ray Service
>      Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor pr>
>      Active: active (running) since Fri 2020-05-08 00:45:13 UTC; 10s ago
>    Main PID: 26559 (v2ray)
>       Tasks: 14 (limit: 9186)
>      Memory: 9.7M
>      CGroup: /system.slice/v2ray.service
>              └─26559 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
> May 08 00:45:13 kali systemd[1]: Started V2Ray Service.
> May 08 00:45:13 kali v2ray[26559]: V2Ray 4.23.1 (V2Fly, a community-driven>
> May 08 00:45:13 kali v2ray[26559]: A unified platform for anti-censorship.
> May 08 00:45:14 kali v2ray[26559]: 2020/05/08 00:45:14 [Info] v2ray.com/co>
> May 08 00:45:14 kali v2ray[26559]: v2ctl> Read config:  /etc/v2ray/config.>
> May 08 00:45:14 kali v2ray[26559]: 2020/05/08 00:45:14 [Warning] v2ray.com>
> root@kali:~# vim /etc/proxychains.conf
> root@kali:~# cp /usr/lib/proxychains3/proxyresolv /usr/bin/
> root@kali:~# proxyresolv www.google.com
> |S-chain|-<>-127.0.0.1:1080-<--timeout
> root@kali:~# proxyresolv www.google.com
> |S-chain|-<>-127.0.0.1:10808-<--timeout
> root@kali:~# proxyresolv www.google.com
> |S-chain|-<>-127.0.0.1:8080-<--timeout
> ```
> 
> proxychains.conf文件如下：
> 
> ```
> # proxychains.conf  VER 3.1
> #
> #        HTTP, SOCKS4, SOCKS5 tunneling proxifier with DNS.
> #	
> 
> # The option below identifies how the ProxyList is treated.
> # only one option should be uncommented at time,
> # otherwise the last appearing option will be accepted
> #
> dynamic_chain
> #
> # Dynamic - Each connection will be done via chained proxies
> # all proxies chained in the order as they appear in the list
> # at least one proxy must be online to play in chain
> # (dead proxies are skipped)
> # otherwise EINTR is returned to the app
> #
> strict_chain
> #
> # Strict - Each connection will be done via chained proxies
> # all proxies chained in the order as they appear in the list
> # all proxies must be online to play in chain
> # otherwise EINTR is returned to the app
> #
> #random_chain
> #
> # Random - Each connection will be done via random proxy
> # (or proxy chain, see  chain_len) from the list.
> # this option is good to test your IDS :)
> 
> # Make sense only if random_chain
> #chain_len = 2
> 
> # Quiet mode (no output from library)
> #quiet_mode
> 
> # Proxy DNS requests - no leak for DNS data
> proxy_dns 
> 
> # Some timeouts in milliseconds
> tcp_read_time_out 15000
> tcp_connect_time_out 8000
> 
> # ProxyList format
> #       type  host  port [user pass]
> #       (values separated by 'tab' or 'blank')
> #
> #
> #        Examples:
> #
> #            	socks5	192.168.67.78	1080	lamer	secret
> #		http	192.168.89.3	8080	justu	hidden
> #	 	socks4	192.168.1.49	1080
> #	        http	192.168.39.93	8080	
> #		
> #
> #       proxy types: http, socks4, socks5
> #        ( auth types supported: "basic"-http  "user/pass"-socks )
> #
> [ProxyList]
> # add proxy here ...
> # meanwile
> # defaults set to "tor"
> #socks4 	127.0.0.1 9050
> socks5	127.0.0.1 8080	
> ```
> 
> v2ray服务器端 config,json 如下：
> 
> ```
> {
>   "inbounds": [{
>     "port": 35255,
>     "protocol": "vmess",
>     "settings": {
>       "clients": [
>         {
>           "id": "ba738807-125e-4fe4-afd6-47de58893202",
>           "level": 1,
>           "alterId": 64
>         }
>       ]
>     }
>   }],
>   "outbounds": [{
>     "protocol": "freedom",
>     "settings": {}
>   },{
>     "protocol": "blackhole",
>     "settings": {},
>     "tag": "blocked"
>   }],
>   "routing": {
>     "rules": [
>       {
>         "type": "field",
>         "ip": ["geoip:private"],
>         "outboundTag": "blocked"
>       }
>     ]
>   }
> }
> ```
> 
> 请教一下：如何设置客户端v2ray配置文件？

have a try .....
https://toutyrater.github.io/
