### ISSUE TITLE
路由器透明代理，微信打开慢

### ISSUE THREAD

**Issue by sunmatus** [v2ray/discussion#50]
小米路由器3，老毛子固件，开启了v2ray透明代理后，微信/企业微信打开极其慢，一直在“连接中”。
请问哪位解决了这个问题？

**Comment by Zhai2333** [comment]
使用 geoip。

**Comment by qiangliu8183** [comment]
手机客户端没一个好用的

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
