### ISSUE TITLE
在heroku上部署最新版（4.2版）成功，但无法打开网页。

### ISSUE THREAD

**Issue by jlzsss** [v2ray/discussion#56]
报错信息如下：
2018/11/08 21:49:32 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://****.herokuapp.com/): 503 Service Unavailable > websocket: bad handshake] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
