### ISSUE TITLE
从4.0.2版本及以上内核v2rayN无法打开网页

### ISSUE THREAD

**Issue by miko7805** [v2ray/discussion#57]
我试了一下，在相同配置文件下，替换内核为3.4.3到4.0 v2rayN可以正常代理
一旦更新到4.0.2以上，包括几小时前的4.1.1v2rayN无法正常代理，也就是网页无限转圈

LOG
A unified platform for anti-censorship.
2018/11/05 21:34:04 [Warning] v2ray.com/core: V2Ray 4.1.1 started
2018/11/05 21:34:05 tcp:127.0.0.1:4103 accepted tcp:www.google.com.hk:443 
2018/11/05 21:38:48 tcp:127.0.0.1:4203 accepted tcp:www.google.com.hk:4

**Comment by FredDai2018** [comment]
大神好，我配置的时候也遇到类似问题
能教教我解决方法么

配置成功 
Vmess-U.S-1(us2-1***xyz:8300)
启动服务(2018/11/16 20:17:13)......
V2Ray v3.36 (die Commanderin) 20180823
A unified platform for anti-censorship.
2018/11/16 20:17:15 [Warning] Core: V2Ray v3.36 started
2018/11/16 20:17:25 tcp:127.0.0.1:54935 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:25 tcp:127.0.0.1:54937 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:25 tcp:127.0.0.1:54938 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:28 tcp:127.0.0.1:54941 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:35 tcp:127.0.0.1:54948 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:35 tcp:127.0.0.1:54949 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:35 tcp:127.0.0.1:54950 accepted tcp:clients1.google.com:443 
2018/11/16 20:17:41 tcp:127.0.0.1:54955 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:15 tcp:127.0.0.1:54987 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:15 tcp:127.0.0.1:54989 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:15 tcp:127.0.0.1:54988 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:22 tcp:127.0.0.1:54995 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:26 tcp:127.0.0.1:55012 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:26 tcp:127.0.0.1:55011 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:26 tcp:127.0.0.1:55013 accepted tcp:clients1.google.com:443 
2018/11/16 20:18:29 tcp:127.0.0.1:55045 accepted tcp:s.360.cn:80

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
