### ISSUE TITLE
请问一下ws+tls+web的情况下，可以开动态端口吗？

### ISSUE THREAD

**Issue by aiyu20181** [v2ray/discussion#58]
在用的时候发现无法同时开启，请问这样做在**理论**上可以吗？

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
