### ISSUE TITLE
最近出现打开网站 意外终止了连接

### ISSUE THREAD

**Issue by Aaron009** [v2ray/discussion#63]
www.google.co.jp 意外终止了连接。 这是要被封的节奏吗？

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
