### ISSUE TITLE
关于日志功能的一点建议

### ISSUE THREAD

**Issue by hzlmy2002** [v2ray/discussion#65]
在一般情况下，v2ray在用了nginx来转发ws的时候v2ray的access.log中记录的全都是127.0.0.1，需要把nginx配置成透明代理才能显示原始ip，虽然也可以通过一一对应时间的方法来查，不过很不方便，不知道哪个人用了多少流量在访问什么东西。
    联想到现阶段的email只被用来统计流量使用情况，因此可以考虑在access.log里面采用email+ip的方法来生成日志。这个功能在多人使用一台服务器的时候尤其重要。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
