### ISSUE TITLE
SockoptObject对于ss生效么？

### ISSUE THREAD

**Issue by nulx8874** [v2ray/discussion#73]
![image](https://user-images.githubusercontent.com/17349950/48689424-7d8a3000-ec05-11e8-97cf-426ad31aa1cf.png)
请问SockoptObject对于ss生效么？
ss-server是有tcpFastOpen的

**Comment by Cwek** [comment]
有，这是对于上层bound的底层传输层的设置。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
