### ISSUE TITLE
Mux嵌套Mux问题

### ISSUE THREAD

**Issue by kxyzw** [v2ray/discussion#75]
假定 `outbound_1` 中设置了: 
```
"proxySettings": {
    "tag": "outbound_2"
}
```
那么对 `outbound_1` 和 `outbound_2` 的 Mux 该如何设置？
如果都开启Mux是否会出现嵌套：`outbound_1`每8个连接封为1个连接，`outbound_2`又再把每8个(各含8个原始连接的)连接封为1个连接，最终承载了64个连接？

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
