### ISSUE TITLE
V2ray在透明代理中配合iptables时DNS的疑问

### ISSUE THREAD

**Issue by a13547** [v2ray/discussion#77]
我的使用环境是这样的：V2ray运行在路由器上作为透明代理，路由器本身内置dnsmasq提供解析服务，使用iptables 把客户端的TCP请求转到V2ray的dokodemo-door，但似乎在DNS解析上总是不太对，导致某些网站的连接被重置，应该是被墙了。因此就有一些疑问，V2ray在路由器上配合iptables运行的时候，TCP请求是如何被传递的呢？是客户端-iptables-V2ray-dns的顺序吗？似乎iptables不能转发域名，那么TCP请求的传递顺序是客户端-dns-iptables-V2ray吗？是不是配置了iptables之后，V2ray的dokodemo-door入口收到的总是ip地址而不包含域名呢？如果设定DNS服务器是路由器的话，客户端发出的DNS请求总是在路由器的dnsmasq里完成的吗？

**Comment by wd** [comment]
https://wdicc.com/go-across-the-gfw/  你看这个是不是对你有帮助。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
