### ISSUE TITLE
问个反向代理的问题

### ISSUE THREAD

**Issue by sunshineplan** [v2ray/discussion#80]
反向代理一般有2台服务器，比如A是内网机，B是公网服务器，设置好后，访问B某个端口即访问A的某个端口。
我的问题是，如果A和B成功配置反向代理并处于开机状态，如果我把A机器上的配置，一模一样的放到C上并运行，会发生什么效果？是不是C上设置的无法生效？如果A这时又下线了会如何？

**Comment by sunshineplan** [comment]
我稍微试了下，如果AB成功设置后，开启C，C的反向代理的确不会生效，但是日志没有异常或者提示。A下线一段时间后，C的反向代理能够生效。

**Comment by VictoriaRaymond** [comment]
A和C会同时生效，你需要多个并发连接才可以测试

**Comment by sunshineplan** [comment]
同时生效我就有点不明白了。
反向代理我的理解就是，要求访问远程服务器B的某个端口时，相当于访问内网A服务器的某一个端口。如果内网C用和内网A同样的配置，即要求远程服务器B的一个端口，映射到2台内网机各自一个端口，这个不可能同时完成的吧。你说的同时生效难道是向2台内网机都发送连接，但连通的其实只有一个？
我的配置如下：
涉及到使用端口的只有配置portal项的远程服务器B，除了反向代理隧道使用的vmess端口外，还有以下任意门的配置：
    {
      "tag": "vnc",
      "port": 1701,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1",
        "port": 5900,
        "network": "tcp"
      }
    },
目的就是当访问远程服务器B的1701端口，即访问内网机A和C的5900端口。
我实际用的时候只能连到一个内网机。

**Comment by sunshineplan** [comment]
或者说，第一个连接是连接A，第二个连接是连接C，我明天再试试。

**Comment by sunshineplan** [comment]
我试了一遍，的确第一个连接连的是A，第二个连接的B。

**Comment by i2Ray** [comment]
B 作为 A和C的负载均衡

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
