### ISSUE TITLE
关于路由选择时DNS查询的问题, 有时过于缓慢

### ISSUE THREAD

**Issue by veekxt** [v2ray/discussion#86]
路由配置中的`domainStrategy`不为`AsIs`时， v2ray可能需要进行DNS查询， 但是有时候这个过程过于缓慢， 直至超时才继续工作。 我之前发过这个问题的issue https://github.com/v2ray/v2ray-core/issues/1254 ， 得到的回复是 **DNS工作不正常**，  当时改了别的DNS可以正常工作了，  但是在国内能"正常工作"的DNS有几个呢 ? 

这段时间我又见过几次别人有这个问题（以及这个 https://github.com/2dust/v2rayN/issues/246 ），它似乎并不常发生， 但是会给普通用户带来非常大的困扰，  这里的DNS查询只是用来做路由选择的， 不应该有这么严重的影响。

网络方面我不是很懂， 想讨论一下在不更改本地dns配置的情况下， 这个问题有没有解决办法， 或折衷的解决办法。 我想过的方法比如设置dns查询的超时， 但也只是在掩盖问题。

**Comment by Cwek** [comment]
建议设置本地DNS做缓冲。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
