### ISSUE TITLE
能否实现端口复用功能？

### ISSUE THREAD

**Issue by F-TD5X** [v2ray/discussion#92]
比如 443 端口同时用于 https 和 vmess ?

> 不想使用 ws 方式

**Comment by v2raycc** [comment]
感觉不现实

**Comment by F-TD5X** [comment]
事实上我甚至想 haproxy 直接非https直接转发v2ray 端口。。。
不过未知bug。。。

**Comment by Cwek** [comment]
有点复杂（涉及协议流分析），ws就是为了而弄出来吧。

**Comment by kslr** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://v2ray.com/chapter_00/install.html). You can also contribute directly by providing a patch – see the [developer manual](https://v2ray.com/developer/intro/guide.html). :)

Thank you!
